//
//  AddSondageWorker.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 7/7/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promises
import SwiftyJSON

class AddSondageWorker
{
  func doSomeWork()
  {
  }
    func connect(eventBus: EventBus) -> Promise<String> {
        return EventBusApiClientTest.Connect(eventBus: eventBus)
    }
    
    func send(eventBus: EventBus, body: Dictionary<String,Any>, channel: String) -> Promise<String> {
        return EventBusApiClientTest.Send(eventBus: eventBus, body: body, channel: channel)
    }
    
}
