//
//  TopicInteractor.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 8/4/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopicBusinessLogic
{
  func doSomething(request: Topic.Something.Request)
}

protocol TopicDataStore
{
  //var name: String { get set }
}

class TopicInteractor: TopicBusinessLogic, TopicDataStore
{
  var presenter: TopicPresentationLogic?
  var worker: TopicWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Topic.Something.Request)
  {
    worker = TopicWorker()
    worker?.doSomeWork()
    
    let response = Topic.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
