//
//  TopicPresenter.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 8/4/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopicPresentationLogic
{
  func presentSomething(response: Topic.Something.Response)
    func presentTopicsSuccess(topics: [Topic1])
    func presentTopicsError(error:String)
}

class TopicPresenter: TopicPresentationLogic
{
    func presentTopicsSuccess(topics: [Topic1]) {
    viewController?.displayTopicsSuccess(topics: topics)

    }
    
    func presentTopicsError(error: String) {
        viewController?.displayTopicsError(error: error)
    }
    
  weak var viewController: TopicDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Topic.Something.Response)
  {
    let viewModel = Topic.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
