//
//  TopicPresenter.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 8/4/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopicPresentationLogic
{
  func presentSomething(response: Topic.Something.Response)
}

class TopicPresenter: TopicPresentationLogic
{
  weak var viewController: TopicDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Topic.Something.Response)
  {
    let viewModel = Topic.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
