//
//  ReactionsPresenter.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 6/9/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReactionsPresentationLogic
{
  func presentSomething(response: Reactions.Something.Response)
}

class ReactionsPresenter: ReactionsPresentationLogic
{
  weak var viewController: ReactionsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Reactions.Something.Response)
  {
    let viewModel = Reactions.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
