//
//  ReactionsInteractor.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 6/9/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReactionsBusinessLogic
{
  func doSomething(request: Reactions.Something.Request)
}

protocol ReactionsDataStore
{
  //var name: String { get set }
}

class ReactionsInteractor: ReactionsBusinessLogic, ReactionsDataStore
{
  var presenter: ReactionsPresentationLogic?
  var worker: ReactionsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Reactions.Something.Request)
  {
    worker = ReactionsWorker()
    worker?.doSomeWork()
    
    let response = Reactions.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
