//
//  VoteSondagePresenter.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 7/8/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VoteSondagePresentationLogic
{
  func presentSomething(response: VoteSondage.Something.Response)
   func sendVoteSondageEventBus(result: String)
   func presentConnexionSuccess(result: String)
}

class VoteSondagePresenter: VoteSondagePresentationLogic
{
    func sendVoteSondageEventBus(result: String) {
                viewController?.displaySendVoteSondageEventBus(result: result)

    }
    
    func presentConnexionSuccess(result: String) {
        viewController?.displayConnexionSuccess(result:result)
    }
    
  weak var viewController: VoteSondageDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: VoteSondage.Something.Response)
  {
    let viewModel = VoteSondage.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
