//
//  VoteSondageInteractor.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 7/8/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VoteSondageBusinessLogic
{
  func doSomething(request: VoteSondage.Something.Request)
}

protocol VoteSondageDataStore
{
  //var name: String { get set }
}

class VoteSondageInteractor: VoteSondageBusinessLogic, VoteSondageDataStore
{
  var presenter: VoteSondagePresentationLogic?
  var worker: VoteSondageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: VoteSondage.Something.Request)
  {
    worker = VoteSondageWorker()
    worker?.doSomeWork()
    
    let response = VoteSondage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
