//
//  AccueilPresenter.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 8/4/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccueilPresentationLogic
{
  func presentSomething(response: Accueil.Something.Response)
}

class AccueilPresenter: AccueilPresentationLogic
{
  weak var viewController: AccueilDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Accueil.Something.Response)
  {
    let viewModel = Accueil.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
