//
//  ProfilPresenter.swift
//  Espace_Collaboratif
//
//  Created by Mehdi on 14/10/2020.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilPresentationLogic
{
  func presentSomething(response: Profil.Something.Response)
}

class ProfilPresenter: ProfilPresentationLogic
{
  weak var viewController: ProfilDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Profil.Something.Response)
  {
    let viewModel = Profil.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
