//
//  RoomRequestInteractor.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 9/6/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RoomRequestBusinessLogic
{
  func doSomething(request: RoomRequest.Something.Request)
    func getRoomRequest(token : String)

}

protocol RoomRequestDataStore
{
  //var name: String { get set }
}

class RoomRequestInteractor: RoomRequestBusinessLogic, RoomRequestDataStore
{
    func getRoomRequest(token: String) {
          worker = RoomRequestWorker()
              worker?.getRoomRequest(token: token).then {
                  roomrequest in
                  
                  self.presenter?.presentRoomRequestSuccess(roomrequest: roomrequest)
              }.catch {
                  error in
                  self.presenter?.presentRoomRequestError(error: error.localizedDescription)
              }
    }
    
  var presenter: RoomRequestPresentationLogic?
  var worker: RoomRequestWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RoomRequest.Something.Request)
  {
    worker = RoomRequestWorker()
    worker?.doSomeWork()
    
    let response = RoomRequest.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
