//
//  RoomRequestWorker.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 9/6/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promises

class RoomRequestWorker
{
    
    func getRoomRequest(token:String) -> Promise<[RoomRequest1]>
    {
        return RoomAPIClient.getroomrequest(token : token)
    }
    
  func doSomeWork()
  {
  }
}
