//
//  AddRoomPresenter.swift
//  Espace_Collaboratif
//
//  Created by mehdi on 4/29/20.
//  Copyright (c) 2020 mehdi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddRoomPresentationLogic
{
    func presentSomething(response: AddRoom.Something.Response)
    func presentUsersSuccess(users: [User])
    func presentUsersError(error: String)
    func presentAddRoomSucess(response : Room1)
    func  presentAddRoomError (error: String)
}

class AddRoomPresenter: AddRoomPresentationLogic
{
    
    
    func presentUsersSuccess(users: [User]) {
        viewController?.presentUsersSuccess(users: users)
        
    }
    
    func presentUsersError(error: String) {
        viewController?.presentUsersError(error: error)
        
    }
    
    
    
    func presentAddRoomSucess(response: Room1) {
        viewController?.presentAddRoomSuccess(room: response)
        
    }
    func presentAddRoomError(error: String) {
        viewController?.presentUsersError(error: error)
        
    }
    
    weak var viewController: AddRoomDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: AddRoom.Something.Response)
    {
        let viewModel = AddRoom.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
